name: Build and publish release

# Build on Mondays at 01:30 UTC
on:
  schedule:
    - cron: '30 1 * * MON'
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  release-data:
    runs-on: ubuntu-22.04
    outputs:
      tag_name: ${{ steps.create-version-and-tag.outputs.tag_name }}
      version_number: ${{ steps.create-version-and-tag.outputs.version_number }}

    # The tag name is vYYYY.MM.DD.hhmm to create simple, easy-to-read "rolling release" versioning
    steps:
      - name: create version and tag
        id: create-version-and-tag
        run: |
          echo "tag_name=$(date +v%Y.%-m.%-d.%-H%M)" >> $GITHUB_OUTPUT
          echo "version_number=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_OUTPUT

  linux:
    runs-on: ubuntu-18.04  # build on the oldest supported LTS so that resulting binaries are compatible with older and newer Linux releases
    needs: release-data
    env:
      TAG_NAME: ${{ needs.release-data.outputs.tag_name }}
      VERSION_NUMBER: ${{ needs.release-data.outputs.version_number }}

    steps:
      - uses: actions/checkout@v3
      - name: update version
        run: |
          echo ${VERSION_NUMBER} > Seamly2D-x86_64.AppImage
      - uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-x86_64.AppImage
          path: Seamly2D-x86_64.AppImage

  macos:
    runs-on: macos-latest
    needs: release-data
    env:
      TAG_NAME: ${{ needs.release-data.outputs.tag_name }}
      VERSION_NUMBER: ${{ needs.release-data.outputs.version_number }}

    steps:
      - uses: actions/checkout@v3
      - name: update version
        run: |
          mkdir out
          echo ${VERSION_NUMBER} > ./out/Seamly2D-macos
      - uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-macos
          path: out/Seamly2D-macos

  windows:
    runs-on: windows-latest
    needs: release-data
    env:
      TAG_NAME: ${{ needs.release-data.outputs.tag_name }}
      VERSION_NUMBER: ${{ needs.release-data.outputs.version_number }}

    steps:
      - uses: actions/checkout@v3
      - name: update version
        shell: bash
        run: |
          echo ${VERSION_NUMBER} > Seamly2D-windows
      - uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-windows
          path: Seamly2D-windows

  publish:
    runs-on: ubuntu-22.04
    needs: [release-data, windows, linux, macos]
    env:
      TAG_NAME: ${{ needs.release-data.outputs.tag_name }}
      VERSION_NUMBER: ${{ needs.release-data.outputs.version_number }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Seamly2D-x86_64.AppImage
      - uses: actions/download-artifact@v3
        with:
          name: Seamly2D-macos
      - uses: actions/download-artifact@v3
        with:
          name: Seamly2D-windows
      - name: create and publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.VERSION_NUMBER }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            Seamly2D-x86_64.AppImage
            Seamly2D-macos
            Seamly2D-windows