name: Build and publish release

# Build on Mondays at 01:30 UTC
on:
  schedule:
    - cron: '30 1 * * MON'
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  release-data:
    runs-on: ubuntu-22.04
    outputs:
      tag_name: ${{ steps.create-name-and-tag.outputs.tag_name }}
      release_name: ${{ steps.create-name-and-tag.outputs.release_name }}

    # The tag name is vYYYY.MM.DD.hhmm to create simple, easy-to-read "rolling release" versioning
    steps:
      - name: create name and tag
        id: create-name-and-tag
        run: |
          echo "tag_name=$(date +v%Y.%-m.%-d.%-H%M)" >> $GITHUB_OUTPUT
          echo "release_name=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_OUTPUT

      - name: create release data
        uses: softprops/action-gh-release@v1
        with:
          tag_name:  ${{ steps.create-name-and-tag.outputs.tag_name }}
          name: ${{ steps.create-name-and-tag.outputs.release_name }}
          draft: true
          generate_release_notes: true

  linux:
    runs-on: ubuntu-18.04  # build on the oldest supported LTS so that resulting binaries are compatible with older and newer Linux releases
    needs: release-data
    env:
      TAG_NAME: ${{ needs.release-data.outputs.tag_name }}
      RELEASE_NAME: ${{ needs.release-data.outputs.release_name }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: update version
        run: |
          echo ${RELEASE_NAME} > Seamly2D-x86_64.AppImage

      - name: upload file to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          fail_on_unmatched_files: true
          files: |
            Seamly2D-x86_64.AppImage

  macos:
    runs-on: macos-latest
    needs: release-data
    env:
      TAG_NAME: ${{ needs.release-data.outputs.tag_name }}
      RELEASE_NAME: ${{ needs.release-data.outputs.release_name }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: update version
        run: |
          echo ${RELEASE_NAME} > ./out/Seamly2D-macos
          zip out/Seamly2D-macos

      - name: upload file to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          fail_on_unmatched_files: true
          files: |
            out/Seamly2D-macos.zip

  windows:
    runs-on: windows-latest
    needs: release-data
    env:
      TAG_NAME: ${{ needs.release-data.outputs.tag_name }}
      RELEASE_NAME: ${{ needs.release-data.outputs.release_name }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: update version
        shell: bash
        run: |
          echo ${RELEASE_NAME} > Seamly2D-windows
          zip Seamly2D-windows

      - name: upload unsigned Seamly2D-windows.zip as release to Github Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          fail_on_unmatched_files: true
          files: |
            Seamly2D-windows.zip
