name: Build and publish release

# Build on Mondays at 01:30 UTC
on:
  schedule:
    - cron: '30 1 * * MON'
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  release-data:
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.release-data.outputs.upload_url }}

    # The tag name is vYYYY.MM.DD.hhmm to create simple, easy-to-read "rolling release" versioning
    steps:
      - name: create name and tag
        id: create-name-and-tag
        run: |
          echo "TAG_NAME=$(date +v%Y.%-m.%-d.%-H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_ENV

      - name: create release data
        # output is 'upload_url'
        id: release-data
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name:  ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: Build auto weekly release - Published full release
          # create published
          draft: false
          # create a full release, not a pre-release
          prerelease: false

  linux:
    runs-on: ubuntu-18.04  # build on the oldest supported LTS so that resulting binaries are compatible with older and newer Linux releases
    needs: release-data
    env:
      UPLOAD_URL: "${{ needs.release-data.outputs.upload_url }}"

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: update version
        run: |
          date +%Y.%-m.%-d.%-H%M
          touch Seamly2D-x86_64.AppImage

      - name: upload file as release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./Seamly2D-x86_64.AppImage
          asset_name: Seamly2D-x86_64.AppImage
          asset_content_type: application/octet-stream

  macos:
    runs-on: macos-latest
    needs: release-data
    env:
      UPLOAD_URL: "${{ needs.release-data.outputs.upload_url }}"

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: update version
        run: |
          date +%Y.%-m.%-d.%-H%M
          touch ./out/Seamly2D-macos.zip

      - name: upload Seamly2D-macos.zip as pre-release to Github Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./out/Seamly2D-macos.zip
          asset_name: Seamly2D-macos.zip
          asset_content_type: application/zip

  windows:
    runs-on: windows-latest
    needs: release-data
    env:
      UPLOAD_URL: "${{ needs.release-data.outputs.upload_url }}"

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: update version
        shell: bash
        run: |
          date +%Y.%-m.%-d.%-H%M
          touch ../windows-build/Seamly2D-windows.zip

      - name: upload unsigned Seamly2D-windows.zip as release to Github Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ../windows-build/Seamly2D-windows.zip
          asset_name: Seamly2D-windows.zip
          asset_content_type: application/zip
