name: CI

on:
  schedule:
    - cron: '30 1 * * MON'
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:


permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-22.04
    outputs:
      version_number: ${{ steps.create-version.outputs.version_number }}

    # The version number is YYYY.MM.DD.hhmm to create simple, easy-to-read "rolling release" versioning
    # for pull requests before merge keep a static version number
    steps:
      - name: create version number
        id: create-version
        run: |
          if [ $GITHUB_EVENT_NAME = 'schedule' ] || [ $GITHUB_EVENT_NAME = 'workflow_dispatch' ] || [ $GITHUB_EVENT_NAME = 'push' ] ; then
            echo "version_number=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_OUTPUT
          else
            echo "version_number=0.6.0.1" >> $GITHUB_OUTPUT
          fi

  linux:
    runs-on: ubuntu-18.04  # build on the oldest supported LTS so that resulting binaries are compatible with older and newer Linux releases
    needs: version
    env:
      VERSION_NUMBER: ${{ needs.version.outputs.version_number }}

    steps:
      - uses: actions/checkout@v3
      - name: update version
        run: |
          echo ${VERSION_NUMBER} > Seamly2D-x86_64.AppImage
      - uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-x86_64.AppImage
          path: Seamly2D-x86_64.AppImage

  macos:
    runs-on: macos-latest
    needs: version
    env:
      VERSION_NUMBER: ${{ needs.version.outputs.version_number }}

    steps:
      - uses: actions/checkout@v3
      - name: update version
        run: |
          mkdir out
          echo ${VERSION_NUMBER} > ./out/Seamly2D-macos
      - uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-macos
          path: out/Seamly2D-macos

  windows:
    runs-on: windows-latest
    needs: version
    env:
      VERSION_NUMBER: ${{ needs.version.outputs.version_number }}

    steps:
      - uses: actions/checkout@v3
      - name: update version
        shell: bash
        run: |
          echo ${VERSION_NUMBER} > Seamly2D-windows
      - uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-windows
          path: Seamly2D-windows

  publish:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-22.04
    needs: [version, windows, linux, macos]
    env:
      VERSION_NUMBER: ${{ needs.version.outputs.version_number }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Seamly2D-x86_64.AppImage
      - uses: actions/download-artifact@v3
        with:
          name: Seamly2D-macos
      - uses: actions/download-artifact@v3
        with:
          name: Seamly2D-windows
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_NUMBER }}
          name: ${{ env.VERSION_NUMBER }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          # push event is triggered after pull request is merged, and in these cases mark as prerelease
          # all other (schedule and manual) are not marked as prerelease
          prerelease: ${{ github.event_name == 'push' }}
          files: |
            Seamly2D-x86_64.AppImage
            Seamly2D-macos
            Seamly2D-windows
